#!/usr/bin/env bash

usage() {
  echo 'usage: api <profile> <action> <endpoint> [...data]'
}

declare profile
declare server
declare -a args

declare -r config_dir="${XDG_CONFIG_DIR:-$HOME/.config}/api-helper"
declare -A colors
colors[red]=$(tput setaf 1)
colors[green]=$(tput setaf 2)
colors[blue]=$(tput setaf 4)
colors[reset]=$(tput sgr0)

color() {
  local color="$1"; shift
  printf '%s' "${colors[$color]}"
  printf '%s\n' "$@"
  printf '%s' "${colors[reset]}"
}

err() { color red "$@" >&2; return 1; }

die() {
  (( $# > 0 )) && err "$@"
  exit 1
}

has() {
  local v=0
  if [[ $1 = '-v' ]]; then
    v=1
    shift
  fi
  for c; do c="${c%% *}"
    if ! command -v "$c" &> /dev/null; then
      (( v > 0 )) && err "$c not found"
      return 1
    fi
  done
}

parse_config_file() {
  local line key val nr=0
  config_err=()
  while IFS= read -r line; do
    (( ++nr ))
    [[ -z "$line" || "$line" = '#'* ]] && continue
    space=${line%%[![:space:]]*}
    line=${line#"$space"}
    key=${line%% *}
    line=${line#"$key"}
    space=${line%%[![:space:]]*}
    val=${line#"$space"}
    if [[ -z "$val" ]]; then
      config_err+=( "  missing value for \"$key\" in config file on line $nr" )
      continue
    fi
    case "$key" in
      server) server="$val" ;;
      *) args+=( "--$key" "$val" ) ;;
    esac
  done
  if (( ${#config_err[@]} > 0 )); then
    err 'there were errors parsing config file:' "${config_err[@]}"
  fi
}

has -v curl || die

case "$1" in
  -h|--help) usage; exit ;;
esac

if (( $# < 3 )); then
  err 'Not enough options specified'
  usage
  die
fi

profile="$1"
if [[ -r "${config_dir}/$profile" ]]; then
  parse_config_file < "${config_dir}/$profile"
else
  die "could not find or open ${config_dir}/$profile"
fi

if [[ -z "$server" ]]; then
  die "server is not defined for $profile"
fi

args+=( --request "${2^^}" )

endpoint="${server/%\/}/${3#\/}"

shift 3

curl -sL "${args[@]}" "$@" "$endpoint"
